
const S={page:localStorage.getItem('raflo_page')||'dashboard',dark:localStorage.getItem('raflo_dark')==='1',moves:JSON.parse(localStorage.getItem('raflo_moves')||'[]'),rec:JSON.parse(localStorage.getItem('raflo_rec')||'[]')};
const $=id=>document.getElementById(id), brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+v||0);
function save(){localStorage.setItem('raflo_moves',JSON.stringify(S.moves));localStorage.setItem('raflo_rec',JSON.stringify(S.rec))}
function drawer(v){$('drawer').classList.toggle('open',v);$('shade').classList.toggle('open',v)}
function theme(){S.dark=!S.dark;document.body.classList.toggle('dark',S.dark);localStorage.setItem('raflo_dark',S.dark?'1':'0')}
const pages=[['dashboard','⌂','Dashboard'],['cash','▣','Livro Caixa'],['debts','◇','Dívidas e Despesas'],['calendar','▦','Calendário Financeiro'],['reports','▥','Relatórios'],['settings','⚙','Configurações']];
$('nav').innerHTML=pages.map(p=>`<button data-p="${p[0]}"><b>${p[1]}</b> ${p[2]}</button>`).join('');
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.p));
function go(p){S.page=p;localStorage.setItem('raflo_page',p);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===p));drawer(false);render()}
function head(t,s=''){return `<div class="ey">RAFLO FINANCE</div><h1>${t}</h1>${s?`<p style="color:var(--muted);margin-top:-11px">${s}</p>`:''}`}
function dashboard(){let i=S.moves.filter(x=>x.t==='in').reduce((a,x)=>a+x.v,0),o=S.moves.filter(x=>x.t==='out').reduce((a,x)=>a+x.v,0);return head('Dashboard','Visão financeira simples e objetiva.')+`<div class="hero"><div><small>SALDO ATUAL DISPONÍVEL</small><div class="big">${brl(i-o)}</div><small>Entradas menos saídas registradas</small></div><div><small>SALDO PROJETADO</small><div class="big">${brl(i-o)}</div><small>Compromissos futuros serão integrados</small></div></div><div class="grid"><div class="card"><div class="label">Receitas recebidas</div><div class="value green">${brl(i)}</div></div><div class="card"><div class="label">Despesas pagas</div><div class="value red">${brl(o)}</div></div><div class="card"><div class="label">A pagar</div><div class="value red">R$ 0,00</div></div><div class="card"><div class="label">A receber</div><div class="value green">R$ 0,00</div></div></div><div class="grid"><div class="card"><div class="label">Dívidas + empréstimos</div><div class="value red">R$ 0,00</div></div><div class="card"><div class="label">Cartões</div><div class="value">0</div></div><div class="card"><div class="label">Resultado do mês</div><div class="value green">${brl(i-o)}</div></div><div class="card"><div class="label">Lançamentos</div><div class="value">${S.moves.length}</div></div></div>`}
function cash(){let i=S.moves.filter(x=>x.t==='in').reduce((a,x)=>a+x.v,0),o=S.moves.filter(x=>x.t==='out').reduce((a,x)=>a+x.v,0);return head('Livro Caixa','Abra o caixa, registre tudo que entra e sai e feche o dia.')+`<div class="card"><div class="ey">CAIXA DIÁRIO</div><h2 style="font-size:25px">${new Date().toLocaleDateString('pt-BR')}</h2><div class="grid"><div><div class="label">Entradas</div><div class="value green">${brl(i)}</div></div><div><div class="label">Saídas</div><div class="value red">${brl(o)}</div></div></div></div><div class="section card"><h2>Registrar movimento</h2><form class="form" onsubmit="addMove(event)"><div class="field"><label>Tipo</label><select id="mt"><option value="in">Entrada</option><option value="out">Saída</option></select></div><div class="field"><label>Valor</label><input id="mv" type="number" step=".01" required></div><div class="field"><label>Descrição</label><input id="md" required></div><div class="field"><label>Origem / destino</label><input id="ms"></div><div class="field full"><button class="btn">Adicionar movimento</button></div></form></div><div class="section card"><h2>Movimentos</h2><div class="list">${S.moves.length?S.moves.slice().reverse().map(x=>`<div class="item"><span class="pill">${x.t==='in'?'ENTRADA':'SAÍDA'}</span><span>${x.d}<small style="display:block;color:var(--muted)">${x.s||''}</small></span><strong class="${x.t==='in'?'green':'red'}">${brl(x.v)}</strong></div>`).join(''):'<div class="empty">Nenhum movimento registrado.</div>'}</div></div>`}
function addMove(e){e.preventDefault();S.moves.push({t:mt.value,v:+mv.value,d:md.value,s:ms.value});save();render()}
function debts(){return head('Dívidas e Despesas','Compromissos organizados em um único lugar.')+`<div class="tabs"><button class="tab active">Visão geral</button><button class="tab">Cartões</button><button class="tab">Empréstimos</button><button class="tab">Recorrentes</button></div><div class="card"><h2>Novo pagamento recorrente</h2><form class="form" onsubmit="addRec(event)"><div class="field"><label>Descrição</label><input id="rd" placeholder="Ex.: aluguel" required></div><div class="field"><label>Credor</label><input id="rc" required></div><div class="field"><label>Valor</label><input id="rv" type="number" step=".01" required></div><div class="field"><label>Dia fixo</label><input id="ry" type="number" min="1" max="31" value="10" required></div><div class="field"><label>Início</label><input id="rs" type="date" required></div><div class="field"><label>Origem do pagamento</label><select id="rx"><option>Caixa</option><option>Conta bancária</option><option>Pix</option><option>Carteira</option></select></div><div class="field full"><button class="btn">Cadastrar recorrente</button></div></form></div><div class="section card"><h2>Recorrentes ativos</h2><div class="list">${S.rec.length?S.rec.map(x=>`<div class="item"><span class="pill">MENSAL</span><span><b>${x.d}</b><small style="display:block;color:var(--muted)">${x.c} • todo dia ${x.y} • ${x.x}</small></span><strong class="red">${brl(x.v)}</strong></div>`).join(''):'<div class="empty">Nenhum pagamento recorrente cadastrado.</div>'}</div></div>`}
function addRec(e){e.preventDefault();S.rec.push({d:rd.value,c:rc.value,v:+rv.value,y:+ry.value,s:rs.value,x:rx.value});save();render()}
function calendar(){return head('Calendário Financeiro','Semanas em destaque, pagamentos e recebimentos consolidados.')+`<div class="card"><div class="row"><div><div class="ey">SEMANA ATUAL</div><h2>Período atual</h2></div><span class="pill">ATUAL</span></div><p style="color:var(--muted)">As receitas da semana abatem o valor necessário para pagamentos. A diária será recalculada conforme o caixa, pagamentos e folgas.</p></div><div class="section">${[1,2,3,4,5].map(n=>`<div class="card section"><div class="row"><div><h2>Semana ${n}</h2><small style="color:var(--muted)">Segunda a domingo • período da semana</small></div><span class="pill">${n===1?'ATUAL':'PLANEJADA'}</span></div><div class="list" style="margin-top:10px"><div class="item"><span class="pill">PAGAR</span><span>Total da semana</span><strong class="red">R$ 0,00</strong></div><div class="item"><span class="pill">RECEBER</span><span>Receitas da semana</span><strong class="green">R$ 0,00</strong></div></div><div class="row" style="margin-top:10px"><b>Saldo devedor: R$ 0,00</b><b class="green">Diária necessária: R$ 0,00</b></div></div>`).join('')}</div>`}
function reports(){return head('Relatórios','Informações semanais, mensais e anuais.')+`<div class="grid"><div class="card"><div class="label">Semanal</div><div class="value">R$ 0,00</div></div><div class="card"><div class="label">Mensal</div><div class="value">R$ 0,00</div></div><div class="card"><div class="label">Anual</div><div class="value">R$ 0,00</div></div><div class="card"><div class="label">Caixa</div><div class="value green">R$ 0,00</div></div></div>`}
function settings(){return head('Configurações','Preferências organizadas por blocos.')+`<div class="grid"><div class="card"><h2>Geral</h2><p style="color:var(--muted)">Moeda, aparência e preferências.</p><button class="btn alt" onclick="theme()">Alternar tema</button></div><div class="card"><h2>Fontes financeiras</h2><p style="color:var(--muted)">Caixa, banco, Pix e carteira.</p></div><div class="card"><h2>Planejamento</h2><p style="color:var(--muted)">Semanas, folgas e diária necessária.</p></div><div class="card"><h2>Conta</h2><p style="color:var(--muted)">Autenticação e segurança.</p></div></div>`}
function render(){let f={dashboard,cash,debts,calendar,reports,settings}[S.page];$('page').innerHTML=f();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.p===S.page))}
document.body.classList.toggle('dark',S.dark);render();
