
const S={page:localStorage.getItem('raflo_page')||'dashboard',dark:localStorage.getItem('raflo_dark')==='1',moves:JSON.parse(localStorage.getItem('raflo_moves')||'[]'),rec:JSON.parse(localStorage.getItem('raflo_rec')||'[]')};
const $=x=>document.getElementById(x), brl=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+v||0);
const pages=[['dashboard','⌂','Dashboard'],['cash','▣','Livro Caixa'],['debts','◇','Dívidas e Despesas'],['calendar','▦','Calendário Financeiro'],['reports','▥','Relatórios'],['settings','⚙','Configurações']];
$('nav').innerHTML=pages.map(p=>`<button data-page="${p[0]}"><b>${p[1]}</b><span>${p[2]}</span></button>`).join('');
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
function go(p){S.page=p;localStorage.setItem('raflo_page',p);closeMenu();render()}
function openMenu(){$('drawer').classList.add('open');$('shade').classList.add('open')}
function closeMenu(){$('drawer').classList.remove('open');$('shade').classList.remove('open')}
function toggleTheme(){S.dark=!S.dark;document.body.classList.toggle('dark',S.dark);localStorage.setItem('raflo_dark',S.dark?'1':'0')}
function save(){localStorage.setItem('raflo_moves',JSON.stringify(S.moves));localStorage.setItem('raflo_rec',JSON.stringify(S.rec))}
function head(t,s){return `<div class="ey">RAFLO FINANCE</div><h1>${t}</h1>${s?`<div class="sub">${s}</div>`:''}`}
function dashboard(){let i=S.moves.filter(x=>x.t==='in').reduce((a,x)=>a+x.v,0),o=S.moves.filter(x=>x.t==='out').reduce((a,x)=>a+x.v,0);return head('Dashboard','Seu panorama financeiro, sem excesso de informação.')+`<div class="hero"><div><small>SALDO DISPONÍVEL</small><div class="big">${brl(i-o)}</div><p>Caixa atual</p></div><div><small>RESULTADO DO MÊS</small><div class="big">${brl(i-o)}</div><p>Receitas − saídas</p></div></div><div class="grid"><div class="card metric"><div class="label">Recebido</div><div class="value green">${brl(i)}</div></div><div class="card metric"><div class="label">Pago</div><div class="value red">${brl(o)}</div></div><div class="card metric"><div class="label">A pagar</div><div class="value red">R$ 0,00</div></div><div class="card metric"><div class="label">A receber</div><div class="value green">R$ 0,00</div></div></div><div class="section card"><div class="row"><div><h2>Hoje</h2><small style="color:var(--muted)">Resumo rápido do caixa</small></div><button class="btn alt" onclick="go('cash')">Abrir caixa</button></div><div class="grid"><div><div class="label">Movimentos</div><div class="value">${S.moves.length}</div></div><div><div class="label">Dívidas abertas</div><div class="value red">R$ 0,00</div></div><div><div class="label">Cartões</div><div class="value">0</div></div><div><div class="label">Diária</div><div class="value">R$ 0,00</div></div></div></div>`}
function cash(){let i=S.moves.filter(x=>x.t==='in').reduce((a,x)=>a+x.v,0),o=S.moves.filter(x=>x.t==='out').reduce((a,x)=>a+x.v,0);return head('Livro Caixa','Registre tudo que realmente entrou ou saiu hoje.')+`<div class="card"><div class="ey">CAIXA DE HOJE</div><div class="row"><h2>${new Date().toLocaleDateString('pt-BR')}</h2><span class="pill">ABERTO</span></div><div class="grid"><div><div class="label">Entradas</div><div class="value green">${brl(i)}</div></div><div><div class="label">Saídas</div><div class="value red">${brl(o)}</div></div><div><div class="label">Saldo líquido</div><div class="value">${brl(i-o)}</div></div><div><div class="label">Movimentos</div><div class="value">${S.moves.length}</div></div></div></div><div class="section card"><h2>Novo movimento</h2><form class="form" onsubmit="addMove(event)"><div class="field"><label>Tipo</label><select id="mt"><option value="in">Entrada</option><option value="out">Saída</option></select></div><div class="field"><label>Valor</label><input id="mv" type="number" step=".01" min="0" required></div><div class="field"><label>Descrição</label><input id="md" placeholder="Ex.: corrida, mercado, pagamento" required></div><div class="field"><label>Origem / destino</label><input id="ms" placeholder="Pessoa, empresa, banco..."></div><div class="field full"><button class="btn">Registrar</button></div></form></div><div class="section card"><h2>Movimentos</h2><div class="list">${S.moves.length?S.moves.slice().reverse().map(x=>`<div class="item"><span class="pill">${x.t==='in'?'ENTRADA':'SAÍDA'}</span><span>${x.d}<small>${x.s||''}</small></span><strong class="${x.t==='in'?'green':'red'}">${brl(x.v)}</strong></div>`).join(''):'<div class="empty">O caixa ainda não possui movimentos.</div>'}</div></div>`}
function addMove(e){e.preventDefault();S.moves.push({t:mt.value,v:+mv.value,d:md.value,s:ms.value});save();render()}
function debts(){return head('Dívidas e Despesas','Todos os compromissos em uma única área.')+`<div class="tabs"><button class="tab active">Resumo</button><button class="tab">Cartões</button><button class="tab">Empréstimos</button><button class="tab">Recorrentes</button></div><div class="grid"><div class="card metric"><div class="label">Em aberto</div><div class="value red">R$ 0,00</div></div><div class="card metric"><div class="label">Este mês</div><div class="value">R$ 0,00</div></div><div class="card metric"><div class="label">Atrasado</div><div class="value red">R$ 0,00</div></div><div class="card metric"><div class="label">Recorrente</div><div class="value">${S.rec.length}</div></div></div><div class="section card"><h2>Pagamento recorrente</h2><p style="color:var(--muted);font-size:12px">Mesmo valor e mesma data mensal. A regra fica salva e gera os compromissos de cada competência.</p><form class="form" onsubmit="addRec(event)"><div class="field"><label>Descrição</label><input id="rd" required></div><div class="field"><label>Credor</label><input id="rc" required></div><div class="field"><label>Valor mensal</label><input id="rv" type="number" step=".01" required></div><div class="field"><label>Dia do vencimento</label><input id="ry" type="number" min="1" max="31" value="10" required></div><div class="field"><label>Início</label><input id="rs" type="date" required></div><div class="field"><label>Origem do pagamento</label><select id="rx"><option>Caixa</option><option>Conta bancária</option><option>Pix</option><option>Carteira</option></select></div><div class="field full"><button class="btn">Salvar recorrente</button></div></form></div><div class="section card"><h2>Recorrentes</h2><div class="list">${S.rec.length?S.rec.map(x=>`<div class="item"><span class="pill">MENSAL</span><span><b>${x.d}</b><small>${x.c} • dia ${x.y} • ${x.x}</small></span><strong class="red">${brl(x.v)}</strong></div>`).join(''):'<div class="empty">Nenhum pagamento recorrente cadastrado.</div>'}</div></div>`}
function addRec(e){e.preventDefault();S.rec.push({d:rd.value,c:rc.value,v:+rv.value,y:+ry.value,s:rs.value,x:rx.value});save();render()}
function calendar(){return head('Calendário Financeiro','A semana atual fica sempre em primeiro plano.')+`<div class="card week current"><div class="row"><div><div class="ey">SEMANA ATUAL</div><h2>Segunda → Domingo</h2></div><span class="pill">HOJE</span></div><div class="grid"><div><div class="label">Total a pagar</div><div class="value red">R$ 0,00</div></div><div><div class="label">Total a receber</div><div class="value green">R$ 0,00</div></div><div><div class="label">Saldo devedor</div><div class="value">R$ 0,00</div></div><div><div class="label">Diária necessária</div><div class="value">R$ 0,00</div></div></div></div><div class="section card"><h2>Semanas do mês</h2><div class="list">${[1,2,3,4,5].map(n=>`<div class="item"><span class="pill">SEM ${n}</span><span>Pagamentos e recebimentos da semana</span><strong>R$ 0,00</strong></div>`).join('')}</div></div>`}
function reports(){return head('Relatórios','Leitura semanal, mensal e anual.')+`<div class="grid"><div class="card metric"><div class="label">Semana</div><div class="value">R$ 0,00</div></div><div class="card metric"><div class="label">Mês</div><div class="value">R$ 0,00</div></div><div class="card metric"><div class="label">Ano</div><div class="value">R$ 0,00</div></div><div class="card metric"><div class="label">Caixa</div><div class="value green">R$ 0,00</div></div></div><div class="section card"><h2>Panorama</h2><div class="empty">Os gráficos serão ligados aos dados reais do Supabase na próxima integração.</div></div>`}
function settings(){return head('Configurações','Poucas opções, organizadas por assunto.')+`<div class="grid"><div class="card"><h2>Aparência</h2><p style="color:var(--muted);font-size:12px">Tema claro ou escuro.</p><button class="btn alt" onclick="toggleTheme()">Alternar tema</button></div><div class="card"><h2>Fontes financeiras</h2><p style="color:var(--muted);font-size:12px">Caixa, conta, Pix e carteira.</p></div><div class="card"><h2>Planejamento</h2><p style="color:var(--muted);font-size:12px">Semanas, folgas e diária.</p></div><div class="card"><h2>Conta</h2><p style="color:var(--muted);font-size:12px">Segurança e acesso.</p></div></div>`}
function render(){document.body.classList.toggle('dark',S.dark);$('page').innerHTML={dashboard,cash,debts,calendar,reports,settings}[S.page]();document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===S.page))}
render();
