const SUPABASE_URL='https://zowmlsusgnzqskuplxcu.supabase.co';
const SUPABASE_KEY='sb_publishable_vkoEbQBCeSDsoFRZxJ4VoA_gVWhQf5M';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let state={transactions:[],debts:[],cards:[],loans:[],recurring:[],cashbooks:[],settings:{}};let ws=null;let current='today';
const $=s=>document.querySelector(s), money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+v||0), iso=d=>new Date(d+'T12:00:00'), today=()=>new Date().toISOString().slice(0,10), uid=()=>crypto.randomUUID();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function normalize(s){const b={transactions:[],debts:[],cards:[],loans:[],recurring:[],cashbooks:[],settings:{}};const x={...b,...(s||{})};for(const k of ['transactions','debts','cards','loans','recurring','cashbooks'])if(!Array.isArray(x[k]))x[k]=[];return x}
async function workspace(){const r=await sb.rpc('get_or_create_my_workspace');if(r.error)throw r.error;return r.data}
async function checkAccess(){const u=(await sb.auth.getUser()).data.user;const r=await sb.from('user_access_controls').select('status,reason').eq('user_id',u.id).maybeSingle();if(r.data&&r.data.status!=='active')throw new Error(`Acesso ${r.data.status}. ${r.data.reason||''}`)}
async function load(){await checkAccess();ws=await workspace();const r=await sb.from('app_state').select('state,updated_at').eq('workspace_id',ws).maybeSingle();if(r.error)throw r.error;state=normalize(r.data?.state);localStorage.setItem('raquor_mobile_state',JSON.stringify(state));render(current)}
async function save(){localStorage.setItem('raquor_mobile_state',JSON.stringify(state));if(!ws)return;const r=await sb.from('app_state').upsert({workspace_id:ws,state,updated_at:new Date().toISOString()},{onConflict:'workspace_id'});if(r.error)console.error(r.error)}
function currentCash(){const c=state.cashbooks?.find(x=>x.date===today());return c?.net??(state.transactions||[]).filter(x=>x.date===today()&&x.status==='pago').reduce((a,x)=>a+(x.type==='receita'?1:-1)*(+x.value||0),0)}
function allMoves(){return state.transactions||[]}
function pending(){return allMoves().filter(x=>x.type==='despesa'&&x.status!=='pago').reduce((a,x)=>a+(+x.value||0),0)}
function cycle(){let start=+(state.settings?.cycleStart||1),len=+(state.settings?.cycleLength||30),now=iso(today()),sd=new Date(now.getFullYear(),now.getMonth(),start,12);if(now<sd)sd=new Date(now.getFullYear(),now.getMonth()-1,start,12);let ed=new Date(sd);ed.setDate(ed.getDate()+len-1);return{start:sd,end:ed}}
function daysLeft(){const c=cycle();return Math.max(1,Math.floor((c.end-iso(today()))/86400000)+1)}
function daily(){const rec=allMoves().filter(x=>x.type==='receita'&&x.status!=='pago'&&iso(x.date)>=iso(today())&&iso(x.date)<=cycle().end).reduce((a,x)=>a+(+x.value||0),0);return Math.max(0,(pending()-Math.max(0,currentCash())-rec)/daysLeft())}
function periodStats(rows){return{totalPay:rows.filter(x=>x.type==='despesa'&&x.status!=='pago').reduce((a,x)=>a+(+x.value||0),0),totalRec:rows.filter(x=>x.type==='receita'&&x.status!=='pago').reduce((a,x)=>a+(+x.value||0),0)}}
function shell(content){return `<div class="page">${content}</div>`}
function todayView(){let d=today(),rows=allMoves().filter(x=>x.date===d);let s=periodStats(rows);return shell(`<div class="hero"><small>SALDO EM CAIXA</small><div class="amount">${money(currentCash())}</div><p>Visão rápida do dia</p></div><div class="grid"><div class="card"><div class="label">A pagar hoje</div><div class="value negative">${money(s.totalPay)}</div></div><div class="card"><div class="label">A receber hoje</div><div class="value positive">${money(s.totalRec)}</div></div><div class="card"><div class="label">Buscar por dia</div><div class="value">${money(daily())}</div></div><div class="card"><div class="label">Dias restantes</div><div class="value">${daysLeft()}</div></div></div><div class="section card"><div class="row"><div><h2>Hoje</h2><div class="muted">${iso(d).toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'})}</div></div><span class="pill">DIA</span></div>${rows.length?rows.map(x=>`<div class="item"><span class="pill ${x.type==='receita'?'green':'red'}">${x.type==='receita'?'RECEBER':'PAGAR'}</span><span><b>${esc(x.person||x.category||'Compromisso')}</b><small>${esc(x.note||x.category||'')}</small></span><strong class="${x.type==='receita'?'positive':'negative'}">${money(x.value)}</strong></div>`).join(''):'<div class="muted">Nenhum lançamento para hoje.</div>'}</div>`)}
function weekView(){let d=iso(today()),day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);let days=[];for(let i=0;i<7;i++){let x=new Date(start);x.setDate(start.getDate()+i);let k=x.toISOString().slice(0,10);days.push({k,x,rows:allMoves().filter(t=>t.date===k)})}let flat=days.flatMap(x=>x.rows),s=periodStats(flat);return shell(`<div class="hero"><small>SEMANA FINANCEIRA</small><div class="amount">${money(Math.max(0,s.totalPay-currentCash()-s.totalRec))}</div><p>${start.toLocaleDateString('pt-BR')} → ${new Date(start.getFullYear(),start.getMonth(),start.getDate()+6).toLocaleDateString('pt-BR')}</p></div><div class="grid"><div class="card"><div class="label">Total a pagar</div><div class="value negative">${money(s.totalPay)}</div></div><div class="card"><div class="label">Total a receber</div><div class="value positive">${money(s.totalRec)}</div></div><div class="card"><div class="label">Caixa</div><div class="value">${money(currentCash())}</div></div><div class="card"><div class="label">Buscar por dia</div><div class="value">${money(daily())}</div></div></div><div class="section card"><h2>Dias da semana</h2>${days.map(q=>{let z=periodStats(q.rows);return `<div class="day"><b>${q.x.toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit'})}</b><span><small class="negative">Pagar ${money(z.totalPay)}</small><small class="positive">Receber ${money(z.totalRec)}</small></span><strong>${money(Math.max(0,z.totalPay-z.totalRec))}</strong></div>`}).join('')}</div>`)}
function monthView(){let now=iso(today()),m=now.getMonth(),y=now.getFullYear(),rows=allMoves().filter(x=>{let d=iso(x.date);return d.getMonth()===m&&d.getFullYear()===y}),s=periodStats(rows),c=cycle();return shell(`<div class="hero"><small>CICLO / MÊS</small><div class="amount">${money(Math.max(0,s.totalPay-currentCash()-s.totalRec))}</div><p>${c.start.toLocaleDateString('pt-BR')} → ${c.end.toLocaleDateString('pt-BR')}</p></div><div class="grid"><div class="card"><div class="label">A pagar</div><div class="value negative">${money(s.totalPay)}</div></div><div class="card"><div class="label">A receber</div><div class="value positive">${money(s.totalRec)}</div></div><div class="card"><div class="label">Caixa</div><div class="value">${money(currentCash())}</div></div><div class="card"><div class="label">Buscar por dia</div><div class="value">${money(daily())}</div></div></div><div class="section card"><div class="row"><h2>${now.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h2><span class="pill">${rows.length} lanç.</span></div><div class="progress"><span style="width:${Math.min(100,Math.max(4,(s.totalRec||0)/(s.totalPay+s.totalRec||1)*100))}%"></span></div><p class="muted">O valor diário é recalculado conforme pagamentos, receitas, dias passados, folgas e caixa disponível.</p></div>`)}
function cycleView(){let c=cycle(),rows=allMoves().filter(x=>{let d=iso(x.date);return d>=c.start&&d<=c.end}),s=periodStats(rows);return shell(`<div class="hero"><small>CICLO FINANCEIRO</small><div class="amount">${money(Math.max(0,s.totalPay-currentCash()-s.totalRec))}</div><p>${c.start.toLocaleDateString('pt-BR')} → ${c.end.toLocaleDateString('pt-BR')} • ${Math.round((c.end-c.start)/86400000)+1} dias</p></div><div class="grid"><div class="card"><div class="label">Compromissos</div><div class="value negative">${money(s.totalPay)}</div></div><div class="card"><div class="label">Receitas</div><div class="value positive">${money(s.totalRec)}</div></div><div class="card"><div class="label">Caixa</div><div class="value">${money(currentCash())}</div></div><div class="card"><div class="label">Buscar por dia</div><div class="value">${money(daily())}</div></div></div><div class="section card"><h2>Resumo do ciclo</h2><div class="item"><span>Total ainda necessário</span><strong class="negative">${money(Math.max(0,s.totalPay-currentCash()-s.totalRec))}</strong></div><div class="item"><span>Dias disponíveis</span><strong>${daysLeft()}</strong></div><div class="item"><span>Meta diária</span><strong>${money(daily())}</strong></div></div>`)}
function assistant(){return shell(`<div class="ai-head"><div><span class="eyebrow">ASSISTENTE FINANCEIRO</span><h2>O que você precisa organizar?</h2><p class="muted">Escolha uma opção ou fale/escreva livremente. O RAQVOR fará perguntas até ter os dados necessários e só registra depois da sua confirmação.</p></div></div><div class="quick-grid">${[['receive','💰 Recebi dinheiro'],['pay','💸 Fiz um pagamento'],['loan_in','🤝 Peguei dinheiro emprestado'],['loan_out','🤲 Emprestei dinheiro'],['card','💳 Fiz compra no cartão'],['debt','🧾 Cadastrei uma dívida'],['expense','🛒 Cadastrei uma despesa'],['other','✦ Outra situação']].map(x=>`<button class="quick" data-ai="${x[0]}">${x[1]}</button>`).join('')}</div><div class="chat card"><div id="chatlog"><div class="bubble ai">Olá. Eu vou organizar a operação com você. Podemos usar respostas rápidas, texto livre ou voz.</div></div><form id="aiform"><input id="aifield" placeholder="Ex.: peguei R$ 1.000 emprestado do João..." autocomplete="off"><button class="primary" title="Enviar">Enviar</button><button type="button" id="mic" class="voice" title="Falar">🎙</button></form><div id="ai-status" class="muted"></div></div>`)}
let ai={intent:null,step:0,data:{},remoteMessages:[],remoteOperation:null};
const flows={receive:[['origem','De onde veio o dinheiro?','text'],['valor','Qual foi o valor recebido?','money'],['data','Em que data recebeu?','date'],['devolver','Precisa devolver esse valor?','choice:sim/não']],pay:[['valor','Qual valor você pagou?','money'],['credor','Para quem ou onde foi o pagamento?','text'],['tipo','O pagamento foi de qual tipo?','choice:dívida/despesa/empréstimo/cartão/outro'],['data','Em que data pagou?','date']],loan_in:[['credor','Quem emprestou o dinheiro?','text'],['valor','Quanto você recebeu?','money'],['tipo','Como pretende devolver?','choice:único/parcelado/recorrente'],['parcelas','Quantas parcelas?','number'],['parcela','Qual o valor de cada parcela?','money'],['juros','Existe juros/custo além do valor recebido? Informe o valor, ou 0.','money'],['inicio','Quando começa a pagar?','date'],['uso','Você já usou esse dinheiro para pagar algo?','choice:sim/não']],loan_out:[['pessoa','Para quem você emprestou?','text'],['valor','Qual valor?','money'],['devolver','Quando espera receber de volta?','date']],card:[['cartao','Qual cartão você usou?','card'],['valor','Qual o valor total da compra?','money'],['parcelas','Em quantas vezes?','number'],['data','Qual a data da compra?','date'],['vencimento','Qual o dia da primeira cobrança?','number'],['descricao','Qual a descrição da compra?','text']],debt:[['credor','Quem é o credor?','text'],['valor','Qual o valor total?','money'],['parcelas','Será único ou parcelado? Informe a quantidade de parcelas.','number'],['parcela','Qual o valor da parcela?','money'],['inicio','Primeiro vencimento?','date'],['tipo','É pessoa, instituição, financiamento ou outra dívida?','text']],expense:[['valor','Qual o valor da despesa?','money'],['descricao','O que foi pago ou comprado?','text'],['credor','Para quem/onde foi?','text'],['data','Qual a data?','date'],['fonte','De onde sairá o dinheiro?','text']]};

async function askRemoteAI(text){
  ai.remoteMessages.push({role:'user',content:[{type:'input_text',text}]});
  const body={messages:ai.remoteMessages,context:{cards:state.cards||[],creditors:[...(state.debts||[]).map(x=>x.creditor),...(state.loans||[]).map(x=>x.person)].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i),cycle:{start:state.settings?.cycleStart||1,length:state.settings?.cycleLength||30},profile:state.settings?.profile||{}}};
  const r=await sb.functions.invoke('raquor-ai',{body});
  if(r.error)throw r.error;
  const out=r.data;if(!out?.assistant_text)throw new Error('Assistente indisponível');
  ai.remoteMessages.push({role:'assistant',content:[{type:'output_text',text:JSON.stringify(out)}]});
  addBubble(out.assistant_text,'ai');
  if(out.ready){ai.remoteOperation=out.operation;$('#chatlog').insertAdjacentHTML('beforeend',`<div class="choice-row"><button class="choice confirm-remote">✓ Confirmar operação</button><button class="choice cancel-remote">Corrigir</button></div>`);$('.confirm-remote').onclick=commitRemoteOperation;$('.cancel-remote').onclick=()=>addBubble('Certo. Diga o que deseja corrigir.','ai')} else {if(Array.isArray(out.choices)&&out.choices.length){const html=`<div class="choice-row">${out.choices.map(c=>`<button type="button" class="choice remote-choice">${esc(c)}</button>`).join('')}</div>`;addBubble(html,'ai',true);document.querySelectorAll('.remote-choice').forEach(b=>b.onclick=async()=>{addBubble(b.textContent,'user');try{await askRemoteAI(b.textContent)}catch(e){addBubble('Não consegui acessar a IA agora. Vou continuar pelo modo guiado.','ai');}})}else if(Array.isArray(out.missing_fields)&&out.missing_fields.length)addBubble('Preciso confirmar: '+out.missing_fields.join(', '),'ai')}
}
async function commitRemoteOperation(){
  const o=ai.remoteOperation;if(!o)return;
  const now=today(),parts=Math.max(1,Number(o.installments)||1),amount=Number(o.amount)||0,part=Number(o.installment_value)||((parts?amount/parts:amount));
  if(o.intent==='receive'){state.transactions.push({id:uid(),date:o.date||now,value:amount,category:'Receita recebida',person:o.creditor||o.source||'Origem não informada',status:'pago',type:'receita',repayable:!!o.repayment_needed,note:'Assistente RAQVOR IA'})}
  else if(o.intent==='pay'||o.intent==='expense'){state.transactions.push({id:uid(),date:o.date||now,value:amount,category:o.kind||'Despesa',person:o.creditor||'',status:o.kind==='pagamento'?'pago':'previsto',type:'despesa',note:'Assistente RAQVOR IA'})}
  else if(o.intent==='card_purchase'){
    const id=uid();state.debts.push({id,cardId:o.card_id||'',creditor:o.creditor||'',kind:'Cartão de crédito',value:amount,totalPayable:o.total_payable||amount,installments:parts,installmentValue:part,firstDate:o.first_due_date||o.date||now,status:'ativo',remaining:o.total_payable||amount,createdAt:now,note:o.description||''});
    for(let i=0;i<parts;i++){const dt=new Date(iso(o.first_due_date||o.date||now));dt.setMonth(dt.getMonth()+i);const date=dt.toISOString().slice(0,10);state.transactions.push({id:uid(),date,value:part,category:o.description||'Compra no cartão',person:o.creditor||'',status:'previsto',type:'despesa',cardId:o.card_id||'',debtId:id,installment:i+1,note:`Assistente RAQVOR • parcela ${i+1}/${parts}`})}
  } else if(o.intent==='loan_received'){
    const loanId=uid(),total=o.total_payable||((part*parts)+Number(o.interest||0));state.loans.push({id:loanId,person:o.creditor||'',value:amount,installments:parts,installmentValue:part,totalPayable:total,firstDate:o.first_due_date||o.date||now,status:'recebido',createdAt:now,note:o.description||'Assistente RAQVOR IA'});state.debts.push({id:uid(),loanId,creditor:o.creditor||'',kind:'Empréstimo',value:amount,totalPayable:total,installments:parts,installmentValue:part,firstDate:o.first_due_date||o.date||now,status:'ativo',remaining:total,createdAt:now});state.transactions.push({id:uid(),date:o.date||now,value:amount,category:'Empréstimo recebido',person:o.creditor||'',status:'pago',type:'receita',loanId,loanPrincipal:true,note:'Assistente RAQVOR IA'});for(let i=0;i<parts;i++){const dt=new Date(iso(o.first_due_date||o.date||now));dt.setMonth(dt.getMonth()+i);state.transactions.push({id:uid(),date:dt.toISOString().slice(0,10),value:part,category:'Empréstimo',person:o.creditor||'',status:'previsto',type:'despesa',loanId,installment:i+1,note:`Parcela ${i+1}/${parts}`})}for(const p of (o.linked_payments||[])){if(p.amount)state.transactions.push({id:uid(),date:p.date||now,value:Number(p.amount),category:p.kind||'Quitação',person:p.creditor||'',status:'pago',type:'despesa',note:'Pagamento vinculado ao empréstimo — Assistente RAQVOR'})}}
  await save();addBubble('✓ Operação confirmada, registrada e sincronizada.','ai');ai={intent:null,step:0,data:{},remoteMessages:[],remoteOperation:null};
}

function addBubble(text,who='ai',raw=false){const log=$('#chatlog');log.insertAdjacentHTML('beforeend',`<div class="bubble ${who}">${raw?text:esc(text)}</div>`);log.scrollTop=log.scrollHeight}
function parseMoney(v){const n=String(v).replace(/[^0-9,.-]/g,'').replace(/\.(?=.*\.)/g,'').replace(',','.');return +n||0}
function nextQuestion(){const f=flows[ai.intent]||[];if(ai.step>=f.length)return finalizeAI();const [key,q,type]=f[ai.step];let html=q;if(type.startsWith('choice:'))html+=`<div class="choice-row">${type.slice(7).split('/').map(v=>`<button type="button" class="choice" data-answer="${esc(v)}">${esc(v)}</button>`).join('')}</div>`;if(type==='card')html+=state.cards.length?`<div class="choice-row">${state.cards.map(c=>`<button type="button" class="choice" data-card="${c.id}">${esc(c.name||c.person||c.bank||'Cartão')}</button>`).join('')}</div>`:'<div class="muted">Nenhum cartão cadastrado. Cadastre no Desktop.</div>';addBubble(html,'ai',true);document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>acceptAnswer(b.dataset.answer||b.dataset.card));}
function startAI(intent){ai={intent,step:0,data:{}};addBubble(document.querySelector(`[data-ai="${intent}"]`)?.textContent||'Vamos organizar isso.','user');nextQuestion()}
function acceptAnswer(v){const f=flows[ai.intent][ai.step];ai.data[f[0]]=v;ai.step++;addBubble(String(v),'user');nextQuestion()}
function tryFreeText(text){if(!ai.intent){const t=text.toLowerCase();if(/cart[aã]o/.test(t))ai.intent='card';else if(/emprest/.test(t)&&/peg/.test(t))ai.intent='loan_in';else if(/emprest/.test(t))ai.intent='loan_out';else if(/receb/.test(t))ai.intent='receive';else if(/pag/.test(t))ai.intent='pay';else if(/d[ií]vida/.test(t))ai.intent='debt';else ai.intent='expense';ai.step=0;addBubble('Entendi. Vou organizar essa operação com perguntas guiadas.','ai')}const f=flows[ai.intent][ai.step];if(!f)return;let v=text;if(f[2]==='money')v=parseMoney(text);if(f[2]==='number')v=parseInt(text.replace(/\D/g,''),10)||0;ai.data[f[0]]=v;ai.step++;nextQuestion()}
function finalizeAI(){const d=ai.data,intent=ai.intent;let summary='';if(intent==='card')summary=`Compra no cartão ${d.cartao||'selecionado'} • ${money(d.valor)} • ${d.parcelas}x • compra em ${d.data} • primeira cobrança dia ${d.vencimento} • ${d.descricao}`;else if(intent==='loan_in')summary=`Empréstimo recebido de ${d.credor}: ${money(d.valor)} • ${d.parcelas}x ${money(d.parcela)} • juros/custo ${money(d.juros)} • início ${d.inicio} • uso do dinheiro: ${d.uso}`;else if(intent==='pay')summary=`Pagamento de ${money(d.valor)} para ${d.credor} • tipo ${d.tipo} • data ${d.data}`;else if(intent==='receive')summary=`Recebimento de ${money(d.valor)} • origem ${d.origem} • data ${d.data} • devolução: ${d.devolver}`;else summary=`Operação ${intent}: ${JSON.stringify(d)}`;ai.pendingSummary=summary;addBubble(`Resumo: ${summary}\n\nConfirmar registro?`,'ai');$('#chatlog').insertAdjacentHTML('beforeend',`<div class="choice-row"><button class="choice confirm-ai">✓ Confirmar</button><button class="choice cancel-ai">Corrigir</button></div>`);$('.confirm-ai').onclick=commitAI;$('.cancel-ai').onclick=()=>{ai.step=Math.max(0,ai.step-1);nextQuestion()}}
async function commitAI(){const d=ai.data,intent=ai.intent,now=today();if(intent==='receive'){state.transactions.push({id:uid(),date:d.data||now,value:+d.valor||0,category:'Receita recebida',person:d.origem,status:'pago',type:'receita',note:'Registrado pelo Assistente RAQVOR',repayable:d.devolver==='sim'})}
else if(intent==='pay'){state.transactions.push({id:uid(),date:d.data||now,value:+d.valor||0,category:d.tipo,person:d.credor,status:'pago',type:'despesa',note:'Pagamento registrado pelo Assistente RAQVOR'})}
else if(intent==='card'){const card=state.cards.find(c=>c.id===d.cartao)||state.cards.find(c=>c.name===d.cartao);const parts=Math.max(1,+d.parcelas||1),total=+d.valor||0,part=total/parts,id=uid();state.debts.push({id,cardId:card?.id,creditor:card?.name||d.cartao,kind:'Cartão de crédito',value:total,totalPayable:total,installments:parts,installmentValue:part,firstDate:d.data||now,status:'ativo',remaining:total,createdAt:now});for(let i=0;i<parts;i++){const dt=new Date(iso(d.data||now));dt.setMonth(dt.getMonth()+i);const date=dt.toISOString().slice(0,10);state.transactions.push({id:uid(),date,value:part,category:d.descricao||'Compra no cartão',person:card?.name||d.cartao,status:'previsto',type:'despesa',cardId:card?.id,debtId:id,installment:i+1,note:`Assistente RAQVOR • parcela ${i+1}/${parts}`})}}
else if(intent==='loan_in'){const parts=Math.max(1,+d.parcelas||1),part=+d.parcela||0,total=part*parts+(+d.juros||0),id=uid();state.loans.push({id,person:d.credor,value:+d.valor||0,installments:parts,installmentValue:part,totalPayable:total,firstDate:d.inicio,status:'recebido',createdAt:now,note:'Criado pelo Assistente RAQVOR'});state.debts.push({id:uid(),loanId:id,creditor:d.credor,kind:'Empréstimo',value:+d.valor||0,totalPayable:total,installments:parts,installmentValue:part,firstDate:d.inicio,status:'ativo',remaining:total,createdAt:now});state.transactions.push({id:uid(),date:now,value:+d.valor||0,category:'Empréstimo recebido',person:d.credor,status:'pago',type:'receita',loanId:id,loanPrincipal:true,note:'Assistente RAQVOR'});for(let i=0;i<parts;i++){const dt=new Date(iso(d.inicio));dt.setMonth(dt.getMonth()+i);state.transactions.push({id:uid(),date:dt.toISOString().slice(0,10),value:part,category:'Empréstimo',person:d.credor,status:'previsto',type:'despesa',loanId:id,installment:i+1,note:`Parcela ${i+1}/${parts}`})}}
else if(intent==='debt'||intent==='expense'){state.transactions.push({id:uid(),date:d.data||d.inicio||now,value:+d.valor||0,category:d.descricao||d.tipo||'Despesa',person:d.credor,status:'previsto',type:'despesa',note:'Assistente RAQVOR'});}
await save();addBubble('✓ Registro confirmado e sincronizado. O calendário, planejamento e indicadores serão recalculados.','ai');ai={intent:null,step:0,data:{}}}
async function openSupport(){const r=await sb.from('support_tickets').select('*').order('created_at',{ascending:false});const tickets=r.data||[];$('#modal').innerHTML=`<div class="modal-box"><div class="row"><div><span class="eyebrow">SUPORTE</span><h2>Central de atendimento</h2><p class="muted">Prazo padrão de resposta: até 72 horas.</p></div><button id="closeSupport" class="close">×</button></div><form id="ticketForm"><input id="tsub" placeholder="Assunto" required><select id="tcat"><option>financeiro</option><option>cartão</option><option>empréstimo</option><option>problema técnico</option><option>outro</option></select><textarea id="tbody" placeholder="Explique o que aconteceu" required></textarea><button class="primary">Abrir chamado</button></form><div class="support-list">${tickets.map(t=>`<div class="ticket"><div class="row"><b>${esc(t.subject)}</b><span class="pill">${esc(t.status)}</span></div><small>${new Date(t.created_at).toLocaleString('pt-BR')}</small><button class="linkbtn" data-ticket="${t.id}">Ver conversa</button></div>`).join('')}</div></div>`;$('#modal').classList.add('open');$('#closeSupport').onclick=()=>$('#modal').classList.remove('open');$('#ticketForm').onsubmit=async e=>{e.preventDefault();const ins=await sb.from('support_tickets').insert({user_id:(await sb.auth.getUser()).data.user.id,subject:$('#tsub').value,category:$('#tcat').value,priority:'normal'}).select().single();if(ins.error)return alert(ins.error.message);await sb.from('support_messages').insert({ticket_id:ins.data.id,sender_user_id:(await sb.auth.getUser()).data.user.id,body:$('#tbody').value,message_type:'text'});openSupport()};document.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>viewTicket(b.dataset.ticket))}
async function viewTicket(id){
  const t=await sb.from('support_tickets').select('*').eq('id',id).single();
  const m=await sb.from('support_messages').select('*').eq('ticket_id',id).order('created_at');
  const currentUser=(await sb.auth.getUser()).data.user;
  const rendered=await Promise.all((m.data||[]).map(async x=>{let body=esc(x.body||'Mensagem de voz');if(x.audio_path){const u=await sb.storage.from('support-audio').createSignedUrl(x.audio_path,300);if(u.data?.signedUrl)body+=`<audio controls preload="none" src="${u.data.signedUrl}" style="width:100%;margin-top:6px"></audio>`}return `<div class="bubble ${x.sender_user_id===currentUser.id?'user':'ai'}">${body}<small>${new Date(x.created_at).toLocaleString('pt-BR')}</small></div>`}));
  $('#modal .modal-box').innerHTML=`<div class="row"><h2>${esc(t.data.subject)}</h2><button id="backSupport" class="close">×</button></div><div class="messages">${rendered.join('')}</div><form id="replyForm"><textarea id="rbody" placeholder="Responder"></textarea><div class="choice-row"><button class="primary">Enviar</button><button type="button" class="voice" id="userVoice">🎙 Enviar voz</button></div><div id="voiceState" class="muted"></div></form>`;
  $('#backSupport').onclick=openSupport;
  $('#replyForm').onsubmit=async e=>{e.preventDefault();const body=$('#rbody').value.trim();if(!body)return;await sb.from('support_messages').insert({ticket_id:id,sender_user_id:currentUser.id,body,message_type:'text'});viewTicket(id)};
  let rec=null,ch=[];
  $('#userVoice').onclick=async()=>{if(rec){rec.stop();return}if(!navigator.mediaDevices?.getUserMedia)return alert('Microfone indisponível.');const st=await navigator.mediaDevices.getUserMedia({audio:true});rec=new MediaRecorder(st);ch=[];$('#voiceState').textContent='Gravando... toque novamente para enviar.';rec.ondataavailable=e=>ch.push(e.data);rec.onstop=async()=>{st.getTracks().forEach(t=>t.stop());const blob=new Blob(ch,{type:'audio/webm'}),path=`${currentUser.id}/${id}-${Date.now()}.webm`;const up=await sb.storage.from('support-audio').upload(path,blob,{contentType:'audio/webm'});if(up.error)alert(up.error.message);else{await sb.from('support_messages').insert({ticket_id:id,sender_user_id:currentUser.id,message_type:'voice',audio_path:path,body:'Mensagem de voz'});viewTicket(id)}rec=null;$('#voiceState').textContent=''};rec.start()}
}
function render(v=current){current=v;$('#title').textContent={today:'Hoje',week:'Semana',month:'Mês',cycle:'Ciclo',assistant:'Assistente'}[v];$('#view').innerHTML=v==='today'?todayView():v==='week'?weekView():v==='month'?monthView():v==='cycle'?cycleView():assistant();document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.v===v));if(v==='assistant'){document.querySelectorAll('[data-ai]').forEach(b=>b.onclick=()=>startAI(b.dataset.ai));$('#aiform').onsubmit=async e=>{e.preventDefault();const t=$('#aifield').value.trim();if(!t)return;addBubble(t,'user');$('#aifield').value='';$('#ai-status').textContent='Consultando assistente...';try{await askRemoteAI(t)}catch(err){tryFreeText(t)}finally{$('#ai-status').textContent=''}};$('#mic').onclick=()=>speech()}}
function speech(){if(!('webkitSpeechRecognition'in window||'SpeechRecognition'in window)){alert('Seu navegador não oferece reconhecimento de voz. Use o teclado ou permita microfone.');return}const R=window.SpeechRecognition||window.webkitSpeechRecognition,r=new R();r.lang='pt-BR';r.onresult=e=>{const t=e.results[0][0].transcript;$('#aifield').value=t};r.start()}
function boot(){sb.auth.getSession().then(async({data})=>{if(!data.session)return auth();try{await start(data.session.user)}catch(e){alert(e.message);await sb.auth.signOut();auth()}})}
async function start(user){document.body.innerHTML=`<main id="app"><header><button id="menu">☰</button><div><small>RAQVOR</small><h1 id="title">Hoje</h1></div><div class="head-actions"><button id="support">?</button><button id="refresh">↻</button></div></header><section id="view"></section><button class="ai-fab" id="aifab">✦</button><nav><button data-v="today" class="active">Hoje</button><button data-v="week">Semana</button><button data-v="month">Mês</button><button data-v="cycle">Ciclo</button></nav><div id="modal" class="modal"></div></main>`;await load();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>render(b.dataset.v));$('#refresh').onclick=()=>load();$('#aifab').onclick=()=>render('assistant');$('#support').onclick=openSupport;$('#menu').onclick=()=>openSupport();sb.channel('raquor-mobile-'+ws).on('postgres_changes',{event:'*',schema:'public',table:'app_state',filter:`workspace_id=eq.${ws}`},()=>load()).subscribe();sb.channel('raquor-access-'+user.id).on('postgres_changes',{event:'*',schema:'public',table:'user_access_controls',filter:`user_id=eq.${user.id}`},p=>{if(p.new?.status&&p.new.status!=='active'){alert('Seu acesso foi bloqueado.');sb.auth.signOut().then(()=>location.reload())}}).subscribe()}
function auth(){document.body.innerHTML=`<div class="auth"><div class="auth-card"><img class="logo" src="assets/raquor-logo.svg"><h1>RAQVOR</h1><p>Seu painel financeiro.</p><form id="login"><label>E-mail<input id="email" type="email" required></label><label>Senha<input id="pass" type="password" required></label><button class="primary">Entrar</button></form><button class="link" id="register">Criar conta</button></div></div>`;$('#login').onsubmit=async e=>{e.preventDefault();const r=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(r.error)alert(r.error.message);else location.reload()};$('#register').onclick=async()=>{const email=prompt('E-mail'),pass=prompt('Senha (mínimo 6 caracteres)');if(!email||!pass)return;const r=await sb.auth.signUp({email,password:pass});if(r.error)alert(r.error.message);else alert('Conta criada. Faça login.')}}
boot();
