const SUPABASE_URL='https://zowmlsusgnzqskuplxcu.supabase.co';
const SUPABASE_KEY='sb_publishable_vkoEbQBCeSDsoFRZxJ4VoA_gVWhQf5M';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true}});
let session=null, users=[], tickets=[], selectedUser=null, selectedTicket=null, recorder=null, chunks=[];
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>d?new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(d)):'—';
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(+v||0);
function layout(body){$('#root').innerHTML=`<div class="admin"><aside class="side"><div class="brand"><img src="./assets/raquor-logo.svg"></div><button class="active" data-tab="overview">Visão geral</button><button data-tab="users">Usuários</button><button data-tab="tickets">Suporte</button><button data-tab="live">Acesso em tempo real</button><button data-tab="audit">Auditoria</button><small>RAQVOR Admin • suporte e operações</small></aside><main class="main">${body}</main></div>`;document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));}
async function ensureAdmin(){const u=session.user;const r=await sb.from('admin_users').select('role,active').eq('user_id',u.id).maybeSingle();if(r.error)throw r.error;if(!r.data?.active)throw new Error('Esta conta não possui acesso administrativo.');return r.data;}
async function loadUsers(){const p=await sb.from('profiles').select('*').order('created_at',{ascending:false});if(p.error)throw p.error;users=p.data||[];const a=await sb.from('user_access_controls').select('*');if(!a.error){const map=new Map((a.data||[]).map(x=>[x.user_id,x]));users=users.map(u=>({...u,access:map.get(u.id)||{status:'active'}}));}}
async function loadTickets(){const r=await sb.from('support_tickets').select('*').order('created_at',{ascending:false});if(r.error)throw r.error;tickets=r.data||[];}
function header(title,sub=''){return `<div class="top"><div><span class="eyebrow">RAQVOR ADMIN</span><h1>${title}</h1>${sub?`<div style="color:#718096;font-size:12px">${sub}</div>`:''}</div><button class="btn secondary" id="logout">Sair</button></div>`}
async function renderTab(tab){try{await loadUsers();await loadTickets();if(tab==='overview')return overview();if(tab==='users')return userTab();if(tab==='tickets')return ticketsTab();if(tab==='live')return liveTab();return auditTab()}catch(e){$('#root').innerHTML=`<div class="login"><div class="card"><h2>RAQVOR Admin</h2><p>${esc(e.message)}</p><button class="btn primary" onclick="location.reload()">Tentar novamente</button></div></div>`}}
function overview(){layout(`${header('Central administrativa','Operação comercial, suporte e segurança')}<section class="kpis"><div class="card"><div class="label">Usuários</div><div class="value">${users.length}</div></div><div class="card"><div class="label">Ativos</div><div class="value positive">${users.filter(u=>(u.access?.status||'active')==='active').length}</div></div><div class="card"><div class="label">Tickets abertos</div><div class="value amber">${tickets.filter(t=>!['resolved','closed'].includes(t.status)).length}</div></div><div class="card"><div class="label">SLA 72h</div><div class="value">${tickets.filter(t=>!['resolved','closed'].includes(t.status)&&new Date(t.sla_due_at)>new Date()).length}</div></div></section><div class="card"><h3>Operação recomendada</h3><p style="color:#718096">Use Usuários para controlar acesso; Suporte para responder tickets por texto/voz; Acesso em tempo real para abrir uma sessão temporária de suporte; Auditoria para rastrear ações administrativas.</p></div>`);bindCommon()}
function userTab(){layout(`${header('Usuários','Acesso, status e suporte')}<div class="grid"><div class="card"><div class="row"><h3>Clientes</h3><input id="search" placeholder="Pesquisar" style="width:150px;height:36px;border:1px solid #dde5ec;border-radius:8px;padding:0 8px"></div><div class="list" id="userlist">${users.map(u=>`<button class="user ${selectedUser?.id===u.id?'selected':''}" data-user="${u.id}"><b>${esc(u.full_name||u.name||u.email||u.id)}</b><small>${esc(u.email||'')} • <span class="${u.access?.status==='active'?'positive':'negative'}">${esc(u.access?.status||'active')}</span></small></button>`).join('')}</div></div><div class="card" id="userdetail"><div class="empty">Selecione um usuário.</div></div></div>`);bindCommon();document.querySelectorAll('[data-user]').forEach(b=>b.onclick=()=>{selectedUser=users.find(u=>u.id===b.dataset.user);userTab()});$('#search').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('[data-user]').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};if(selectedUser)showUserDetail(selectedUser.id)}
function showUserDetail(id){const u=users.find(x=>x.id===id);const d=$('#userdetail');if(!d)return;d.innerHTML=`<div class="row"><div><span class="eyebrow">CLIENTE</span><h2>${esc(u.full_name||u.name||u.email||id)}</h2><div style="color:#718096;font-size:12px">${esc(u.email||'')}</div></div><span class="pill ${u.access?.status==='active'?'green':'red'}">${esc(u.access?.status||'active')}</span></div><hr style="border:0;border-top:1px solid #e8edf3;margin:16px 0"><p style="font-size:12px;color:#718096">ID: ${esc(id)}</p><div class="row"><button class="btn primary" id="grant">Abrir acesso de suporte por 30 min</button><button class="btn ${u.access?.status==='active'?'danger':'primary'}" id="toggle">${u.access?.status==='active'?'Bloquear acesso':'Reativar acesso'}</button></div>`;$('#grant').onclick=()=>grantSupport(id);$('#toggle').onclick=()=>toggleAccess(id,u.access?.status)}
async function toggleAccess(id,status){const next=status==='active'?'blocked':'active';const r=await sb.from('user_access_controls').upsert({user_id:id,status:next,reason:next==='blocked'?'Bloqueado pelo suporte':'Acesso reativado',changed_by:session.user.id,changed_at:new Date().toISOString()});if(r.error)alert(r.error.message);else{await sb.from('admin_audit_log').insert({admin_user_id:session.user.id,action:next==='blocked'?'user_blocked':'user_unblocked',target_user_id:id,metadata:{from:status,to:next}});selectedUser=users.find(x=>x.id===id);await userTab()}}
async function grantSupport(id){const r=await sb.from('support_access_sessions').insert({admin_user_id:session.user.id,target_user_id:id,purpose:'customer_support',expires_at:new Date(Date.now()+30*60*1000).toISOString()}).select().single();if(r.error)alert(r.error.message);else{await sb.from('admin_audit_log').insert({admin_user_id:session.user.id,action:'support_access_granted',target_user_id:id,metadata:{session_id:r.data.id,minutes:30}});alert('Acesso de suporte liberado por 30 minutos. Use a aba Acesso em tempo real.')}}
function ticketsTab(){layout(`${header('Central de suporte','SLA padrão de até 72 horas')}<div class="grid"><div class="card"><div class="list">${tickets.map(t=>`<button class="ticket" data-ticket="${t.id}"><div class="row"><b>${esc(t.subject)}</b><span class="pill ${t.status==='open'?'amber':'green'}">${esc(t.status)}</span></div><small>${esc(t.category)} • ${fmt(t.created_at)} • SLA ${fmt(t.sla_due_at)}</small></button>`).join('')}</div></div><div class="card" id="ticketdetail"><div class="empty">Selecione um ticket.</div></div></div>`);bindCommon();document.querySelectorAll('[data-ticket]').forEach(b=>b.onclick=()=>{selectedTicket=tickets.find(t=>t.id===b.dataset.ticket);showTicket()});}
async function showTicket(){const t=selectedTicket,d=$('#ticketdetail');if(!d)return;const r=await sb.from('support_messages').select('*').eq('ticket_id',t.id).order('created_at');const msgs=r.data||[];d.innerHTML=`<div class="row"><div><span class="eyebrow">TICKET</span><h2>${esc(t.subject)}</h2><div style="color:#718096;font-size:11px">${esc(t.category)} • prioridade ${esc(t.priority)} • SLA ${fmt(t.sla_due_at)}</div></div><select id="tstatus"><option ${t.status==='open'?'selected':''}>open</option><option ${t.status==='in_progress'?'selected':''}>in_progress</option><option ${t.status==='waiting_user'?'selected':''}>waiting_user</option><option ${t.status==='resolved'?'selected':''}>resolved</option><option ${t.status==='closed'?'selected':''}>closed</option></select></div><div class="messages">${msgs.map(m=>`<div class="msg ${m.sender_user_id===session.user.id?'admin':''}"><b>${m.sender_user_id===session.user.id?'Suporte':'Usuário'}</b><div>${esc(m.body||'Mensagem de voz')}</div><small>${fmt(m.created_at)}</small></div>`).join('')}</div><div class="composer"><textarea id="reply" placeholder="Responder ao usuário..."></textarea><button class="btn primary" id="send">Enviar</button><button class="btn secondary" id="voice">🎙 Voz</button></div><div id="recordstate" style="font-size:10px;color:#718096;margin-top:6px"></div>`;$('#tstatus').onchange=async e=>{await sb.from('support_tickets').update({status:e.target.value,updated_at:new Date().toISOString()}).eq('id',t.id);t.status=e.target.value};$('#send').onclick=sendReply;$('#voice').onclick=recordVoice}
async function sendReply(){const body=$('#reply').value.trim();if(!body)return;const r=await sb.from('support_messages').insert({ticket_id:selectedTicket.id,sender_user_id:session.user.id,body,message_type:'text'});if(r.error)alert(r.error.message);else{await sb.from('support_tickets').update({status:'in_progress',updated_at:new Date().toISOString()}).eq('id',selectedTicket.id);showTicket()}}
async function recordVoice(){if(recorder){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia){alert('Seu navegador não permite gravação de áudio.');return}const stream=await navigator.mediaDevices.getUserMedia({audio:true});recorder=new MediaRecorder(stream);chunks=[];$('#recordstate').textContent='Gravando... toque novamente para finalizar.';recorder.ondataavailable=e=>chunks.push(e.data);recorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks,{type:'audio/webm'});const path=`${selectedTicket.user_id}/${selectedTicket.id}-${Date.now()}.webm`;const up=await sb.storage.from('support-audio').upload(path,blob,{contentType:'audio/webm',upsert:false});if(up.error){alert(up.error.message)}else{const r=await sb.from('support_messages').insert({ticket_id:selectedTicket.id,sender_user_id:session.user.id,message_type:'voice',audio_path:path,body:'Mensagem de voz do suporte'});if(r.error)alert(r.error.message);else showTicket()}recorder=null;$('#recordstate').textContent=''};recorder.start()}
async function liveTab(){layout(`${header('Acesso em tempo real','Sessões temporárias para diagnóstico, sempre auditadas')}<div class="card"><div class="row"><div><h3>Usuário selecionado</h3><div style="color:#718096;font-size:11px">${selectedUser?esc(selectedUser.email||selectedUser.id):'Nenhum'}</div></div><button class="btn secondary" id="choose">Escolher usuário</button></div><div id="livebox" style="margin-top:12px"><div class="empty">Conceda uma sessão de suporte na aba Usuários e selecione o cliente.</div></div></div>`);bindCommon();$('#choose').onclick=()=>userTab();if(selectedUser){const w=await sb.from('finance_workspaces').select('id').eq('owner_user_id',selectedUser.id).maybeSingle();if(!w.data)return;const s=await sb.from('support_access_sessions').select('*').eq('target_user_id',selectedUser.id).is('revoked_at',null).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(1).maybeSingle();if(s.data){const a=await sb.from('app_state').select('state,updated_at').eq('workspace_id',w.data.id).maybeSingle();$('#livebox').innerHTML=`<div class="live">${esc(JSON.stringify(a.data?.state||{},null,2))}</div><div style="margin-top:8px"><button class="btn danger" id="revoke">Revogar sessão</button></div>`;$('#revoke').onclick=async()=>{await sb.from('support_access_sessions').update({revoked_at:new Date().toISOString()}).eq('id',s.data.id);liveTab()};sb.channel('admin-live-'+w.data.id).on('postgres_changes',{event:'*',schema:'public',table:'app_state',filter:`workspace_id=eq.${w.data.id}`},p=>{$('#livebox .live').textContent=JSON.stringify(p.new?.state||{},null,2)}).subscribe()}}}
async function auditTab(){const r=await sb.from('admin_audit_log').select('*').order('created_at',{ascending:false}).limit(100);const rows=r.data||[];layout(`${header('Auditoria','Registro das ações administrativas')}<div class="card"><table class="table"><thead><tr><th>Data</th><th>Ação</th><th>Usuário</th><th>Detalhes</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${fmt(x.created_at)}</td><td>${esc(x.action)}</td><td>${esc(x.target_user_id||'—')}</td><td>${esc(JSON.stringify(x.metadata))}</td></tr>`).join('')}</tbody></table></div>`);bindCommon()}
function bindCommon(){$('#logout')?.addEventListener('click',async()=>{await sb.auth.signOut();location.reload()});}
async function boot(){const s=await sb.auth.getSession();if(!s.data.session){return login()}session=s.data.session;await ensureAdmin();renderTab('overview')}
function login(){$('#root').innerHTML=`<div class="login"><div class="card"><img src="./assets/raquor-logo.svg" style="width:150px;display:block;margin:auto"><h2>Central Administrativa</h2><p style="color:#718096;font-size:12px">Acesso restrito à equipe autorizada.</p><form id="form"><div class="field"><label>E-mail</label><input id="email" type="email" required></div><div class="field"><label>Senha</label><input id="pass" type="password" required></div><button class="btn primary">Entrar</button></form></div></div>`;$('#form').onsubmit=async e=>{e.preventDefault();const r=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#pass').value});if(r.error)return alert(r.error.message);location.reload()}}
boot().catch(e=>login());
